[tool.black]
line-length = 100

[tool.pixi.workspace]
name = "stretch_ai"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
SAM-2 = { path = "third_party/segment-anything-2", editable = false }
stretch_ai = {path = "src", extras = ["dev"], editable = true }

[tool.pixi.system-requirements]
libc = "2.31"

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.10.*"
setuptools = "69.5.1.*"
overrides = "*"
